baseURL = 'http://thisismydemo.cloud/'
languageCode = 'en-us'
title = 'This Is My Demo'

paginate = "10"                  # Number of posts per page
theme = "mainroad"
disqusShortname = "thisismydemo-cloud"             # Enable comments by entering your Disqus shortname
googleAnalytics = "G-C78KZ1DN40" # Enable Google Analytics by entering your tracking id

[Author]
name = "Kristopher J Turner"
bio = "Kristopher Turner is a Microsoft MVP in Azure, a Microsoft Certified Trainer (MCT), and a Product Technology Architect at TierPoint, where he focuses on delivering innovative cloud and infrastructure solutions. With expertise spanning Azure Stack HCI, Azure Arc, Kubernetes, and disaster recovery strategies using ASR, Kristopher bridges on-premises and cloud technologies to drive digital transformation. A sought-after speaker and thought leader, he frequently presents on hybrid architectures, cloud-native technologies, and monitoring solutions, sharing insights from his extensive experience in modern IT infrastructure."
avatar = "img/me.jpg"

[Params]
description = "Another blog about clouds... Private Clouds, Public Clouds, Hybrid Clouds, and pretty little fluffy clouds?" # Description of your site
opengraph = true
twitter_cards = true
readmore = false                                 # Show "Read more" button in list if true
authorbox = true
pager = true
post_meta = ["date", "categories"]               # Order of post meta information
mainSections = ["post", "docs"]


[Params.logo]
subtitle = "Another blog about clouds... Private Clouds, Public Clouds, Hybrid Clouds, and pretty little fluffy clouds?" # Logo subtitle

[Params.sidebar]
home = "right"    # Configure layout for home page
list = "right"   # Configure layout for list pages
single = "right" # Configure layout for single pages
# Enable widgets in given order
widgets = ["search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets.social]
# Enable parts of social widget
linkedin = "KristopherJTurner"
github = "thisismydemo"

[Params.widgets]
recent_num = 5       # Set the number of articles in the "Recent articles" widget
tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

[markup]
defaultMarkdownHandler = 'goldmark'
[markup.goldmark]
[markup.goldmark.renderer]
# change to 'true' if you need to render raw HTML within your markdown content
unsafe = true

[Languages]
[Languages.en]
weight = 1